### ISSUE TITLE
Add support for elasticsearch dashboard backup

### ISSUE THREAD

**Issue by hmsayem** [stashed/project#33]

**Comment by ishtiaqhimel** [comment]
https://github.com/kubedb/db-client-go/pull/81
https://github.com/kubedb/db-client-go/pull/82
https://github.com/stashed/elasticsearch/pull/1461
https://github.com/stashed/elasticsearch/pull/1460
https://github.com/stashed/elasticsearch/pull/1459
https://github.com/stashed/installer/pull/325
https://github.com/stashed/enterprise/pull/244
